### PR TITLE
Added version and stratum checks for incoming packets.

### LINKED ISSUE #194: Validation of Parsed Packets
Reported by jsha

In ntp-proto/src/packet.rs, there are some input fields that could be validated against [limits in the specification](https://datatracker.ietf.org/doc/html/rfc5905#section-7.2) but do not appear to be:

- Version should be 4
- Stratum should be less than or equal to MAXSTRAT
- Poll should be validated against MINPOLL and MAXPOLL

### PR DESCRIPTION
**Pull request by davidv1992**
Fixes #194

### CODE REVIEW

**Comment by djc** [comment]
Should we instead make NtpHeader::deserialize() fallible?

**Comment by davidv1992** [comment]
I don't think that that is a proper solution, packets with a stratum outside of the specified ranges still have a valid interpretation, they just shouldn't be used to synchronize with. The same holds for non-supported versions.

**Comment by djc** [comment]
@jsha any thoughts on that?

**Comment by rnijveld** [comment]
Personally I would prefer to fail early (i.e. during parsing) rather than late. It would add additional value to the type in that it always represents a somewhat usable packet, instead of one where we basically already know that we shouldn't use it (but where a programmer might forget to check).

**Comment by djc** [comment]
> Personally I would prefer to fail early (i.e. during parsing) rather than late. It would add additional value to the type in that it always represents a somewhat usable packet, instead of one where we basically already know that we shouldn't use it (but where a programmer might forget to check).

Yes, exactly.

**Review by folkertdev — APPROVED** [review]

**Pull request merged**
