### PR TITLE
Switch to SO_TIMESTAMPNS as SO_TIMESTAMPNS_NEW is not defined on all

### PR DESCRIPTION
**Pull request by davidv1992**
platforms.

### CODE REVIEW

**Comment by davidv1992** [comment]
Please ignore the codecov failure for now, we still need to configure some better criteria for it.

**Comment by folkertdev** [comment]
sure, so are there any potential downsides to using this (older?) variant?

**Comment by davidv1992** [comment]
@rnijveld If I remember our conversation correctly there is not really a downside to using the more general SO_TIMESTAMPNS, but could you confirm this?

**Comment by rnijveld** [comment]
@davidv1992 It should be fine, I believe it depends on the size of libc::time_t whether `SO_TIMESTAMPNS` refers to `*_OLD` or `*_NEW`. This does change the struct that is used for the control message, but in practice the resulting struct definition is exactly the same.

**Comment by rnijveld** [comment]
Just for extra reference, see: https://www.kernel.org/doc/Documentation/networking/timestamping.txt

One thing to take care of is that `SO_TIMESTAMPNS_OLD` will return invalid timestamps on 32-bit machines after 2038

**Comment by davidv1992** [comment]
Given the timeline for that I am not too worried about that personally, and suggest we move forward with merging this.

**Pull request merged**
